version: "3"

services:

  nodejs:
    image: node:12.14.1
    volumes:
      - ./:/html
    working_dir: /html
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c "npm install & npm run dev"
